ansible-collection/inventory/group_vars/backup_location/create.yaml
ansible-collection/plugins/modules/px_backup/backup_location.py

The code was missing azure environemnt variable, added that in the module code
Closes #
Edited the image since it had creds

PB-8816: Adding azure_environment variable for creation of azure backup location

---

ansible-collection/examples/backup_location/delete.yaml
ansible-collection/inventory/group_vars/backup_location/delete.yaml

Removes unwanted variables which are not used/passed, these variables are never used for any of the backup locations. Hence, removing them to avoid confusion.
Closes #

PB-8842: Removing unwanted variables from examples and inventory

---

ansible-collection/examples/backup_location/inspect.yaml

While testing saw that the messages in the playbook was not getting populated properly, detailed analysis is present in the JIRA ticket. Added these changes since we need to give a proper working demo 
Closes #

PB-8867: Modifying the playbook message for inspect backup location in order to adhere to all types of backup locations

---

ansible-collection/examples/backup_location/validate.yaml
ansible-collection/inventory/group_vars/backup_location/validate.yaml

Modifying playbook and inventory to make sure backup location validation is working fine, removed fields which are not required and necessary. 
Closes #

Modifying examples and inventory for validation of backup location

---

ansible-collection/examples/backup_location/delete.yaml
ansible-collection/examples/backup_location/update.yaml
ansible-collection/examples/backup_location/validate.yaml
ansible-collection/inventory/group_vars/backup_location/update.yaml
ansible-collection/inventory/group_vars/backup_location/validate.yaml

Modifying the playbook to support the updation of the backup location
Closes #

Modifying playbook for updation of backup locaitons

---

ansible-collection/examples/backup_location/update_ownership.yaml
ansible-collection/inventory/group_vars/backup_location/update_ownership.yaml

Making some changes in the playbooks and inventory for the operations to run successfully
Closes #
Updation for all the backup location for ownership went through

Making changes in the bl update ownership for the sample playbooks to run successfully

---

ansible-collection/examples/cluster/create.yaml
ansible-collection/examples/cluster/delete.yaml
ansible-collection/examples/cluster/enumerate.yaml
ansible-collection/examples/cluster/inspect.yaml
ansible-collection/examples/cluster/share.yaml
ansible-collection/examples/cluster/unshare.yaml
ansible-collection/examples/cluster/update.yaml
ansible-collection/examples/cluster/update_ownership.yaml
ansible-collection/inventory/group_vars/backup_location/enumerate.yaml
ansible-collection/inventory/group_vars/cluster/create.yaml
ansible-collection/inventory/group_vars/cluster/delete.yaml
ansible-collection/inventory/group_vars/cluster/enumerate.yaml
ansible-collection/inventory/group_vars/cluster/inspect.yaml
ansible-collection/inventory/group_vars/cluster/share.yaml
ansible-collection/inventory/group_vars/cluster/unshare.yaml
ansible-collection/inventory/group_vars/cluster/update.yaml
ansible-collection/inventory/group_vars/cluster/update_ownership.yaml
ansible-collection/plugins/modules/px_backup/cluster.py

**What this PR does / why we need it**: Add cluster ansible module, playbooks and inventory

PB-8755: Cluster ansible module and playbooks

---

ansible-collection/examples/restore/create.yaml
ansible-collection/examples/restore/delete.yaml
ansible-collection/examples/restore/enumerate.yaml
ansible-collection/examples/restore/inspect.yaml
ansible-collection/inventory/group_vars/restore/create.yaml
ansible-collection/inventory/group_vars/restore/delete.yaml
ansible-collection/inventory/group_vars/restore/enumerate.yaml
ansible-collection/inventory/group_vars/restore/inspect.yaml
ansible-collection/plugins/modules/px_backup/restore.py

This PR brings in the entire Restore Module along with sample playbooks for create, delete, inspect and enumerate
Closes #

PB-8892: Entire Restore Module along with sample playbooks for create, delete, inspect and enumerate

---

ansible-collection/examples/cloud_credential/enumerate.yaml
ansible-collection/examples/combined/combined.yaml
ansible-collection/inventory/group_vars/cloud_credential/enumerate_vars.yaml

- Cloud credential enumerate
- Combined playbook fixes

PB-8755 part2: Playbook fixes

---

README.md
ansible-collection/docs/README.md
ansible-collection/docs/modules/auth.md
ansible-collection/docs/modules/backup.md
ansible-collection/docs/modules/backup_location.md
ansible-collection/docs/modules/backup_schedule.md
ansible-collection/docs/modules/cloud_credential.md
ansible-collection/docs/modules/cluster.md
ansible-collection/docs/modules/restore.md
ansible-collection/inventory/group_vars/backup_location/enumerate.yaml
ansible-collection/inventory/group_vars/common/all.yaml
ansible-collection/plugins/modules/px_backup/auth.py
ansible-collection/plugins/modules/px_backup/backup.py
ansible-collection/plugins/modules/px_backup/backup_schedule.py
ansible-collection/plugins/modules/px_backup/restore.py

documentation for ansible collection

documentation

---

README.md
ansible-collection/docs/README.md
ansible-collection/docs/modules/auth.md
ansible-collection/docs/modules/backup.md
ansible-collection/docs/modules/backup_location.md
ansible-collection/docs/modules/backup_schedule.md
ansible-collection/docs/modules/cloud_credential.md
ansible-collection/docs/modules/cluster.md
ansible-collection/docs/modules/restore.md
ansible-collection/inventory/group_vars/backup_location/enumerate.yaml
ansible-collection/inventory/group_vars/common/all.yaml
ansible-collection/plugins/modules/px_backup/auth.py
ansible-collection/plugins/modules/px_backup/backup.py
ansible-collection/plugins/modules/px_backup/backup_schedule.py
ansible-collection/plugins/modules/px_backup/restore.py

documentation changes for ansible module changes

documentation for ansible modules

---

README.md
ansible-collection/docs/modules/auth.md
ansible-collection/docs/modules/backup.md
ansible-collection/docs/modules/backup_location.md
ansible-collection/docs/modules/backup_schedule.md
ansible-collection/docs/modules/cloud_credential.md
ansible-collection/docs/modules/cluster.md
ansible-collection/docs/modules/restore.md

change in ansible galaxy import

documentation change

---

ansible-collection/docs/README.md
ansible-collection/docs/modules/rule.md

**What this PR does / why we need it**: Add documentation for rule module
Closes #PB-9076

PB-9076-part2: Documentation for rule module

---

ansible-collection/examples/rule/create.yaml
ansible-collection/examples/rule/delete.yaml
ansible-collection/examples/rule/enumerate.yaml
ansible-collection/examples/rule/inspect.yaml
ansible-collection/examples/rule/update.yaml
ansible-collection/examples/rule/update_ownership.yaml
ansible-collection/inventory/group_vars/rule/create.yaml
ansible-collection/inventory/group_vars/rule/delete.yaml
ansible-collection/inventory/group_vars/rule/enumerate.yaml
ansible-collection/inventory/group_vars/rule/inspect.yaml
ansible-collection/inventory/group_vars/rule/update.yaml
ansible-collection/inventory/group_vars/rule/update_ownership.yaml
ansible-collection/plugins/modules/px_backup/rule.py

**What this PR does / why we need it**: Add module and playbooks for rule operations:
1. 'CREATE' creates a new rule
2. 'UPDATE' modifies an existing rule
3. 'DELETE' removes a rule
4. 'INSPECT_ONE' retrieves details of a specific rule
5. 'INSPECT_ALL' lists all rules
6. 'UPDATE_OWNERSHIP' updates ownership settings of a rule
Closes #PB-8736
```
{"metadata":{"name":"rule-2","uid":"461071ca-ae5c-4d3e-90fa-ab9cf078d155","org_id":"default","create_time":{"seconds":1734000969,"nanos":879124997,"timestamp":"12 Dec 2024, 04:26 PM"},"last_update_time":{"seconds":1734364648,"nanos":738442688,"timestamp":"16 Dec 2024, 09:27 PM"},"labels":{"app":"mysql","environment":"production"},"create_time_in_sec":1734000969,"owners …
```

PB-8736: Ansible module and playbooks for rule object

---

ansible-collection/docs/README.md
ansible-collection/docs/modules/role.md
ansible-collection/examples/role/create.yaml
ansible-collection/examples/role/delete.yaml
ansible-collection/examples/role/enumerate.yaml
ansible-collection/examples/role/inspect.yaml
ansible-collection/examples/role/permission.yaml
ansible-collection/examples/role/update.yaml
ansible-collection/examples/rule/delete.yaml
ansible-collection/examples/rule/enumerate.yaml
ansible-collection/inventory/group_vars/role/create.yaml
ansible-collection/inventory/group_vars/role/delete.yaml
ansible-collection/inventory/group_vars/role/enumerate.yaml
ansible-collection/inventory/group_vars/role/inspect.yaml
ansible-collection/inventory/group_vars/role/update.yaml
ansible-collection/inventory/group_vars/rule/inspect.yaml
ansible-collection/plugins/modules/role.py
ansible-collection/plugins/modules/rule.py

**What this PR does / why we need it**: Add module, doc and playbooks for role operations:
'CREATE' creates a new role
'UPDATE' modifies an existing role
'DELETE' removes a role
'INSPECT_ONE' retrieves details of a specific role
'INSPECT_ALL' lists all roles
'PERMISSION' returns list of service,apis permission 
Closes #PB-8938
**Testing**:
Permission
```
TASK [Get list of permissions] *****************************************************************************************************************************
ok: [localhost]
TASK [Display role list summary] ***************************************************************************************************************************
ok: [localhost] => {
"msg": [
"Total rules found: 8"
]
}
TASK …
```

PB-8938: Role object module, playbooks and doc

---

ansible-collection/docs/modules/receiver.md
ansible-collection/docs/modules/recipient.md
ansible-collection/examples/receiver/create.yaml
ansible-collection/examples/receiver/delete.yaml
ansible-collection/examples/receiver/enumerate.yaml
ansible-collection/examples/receiver/inspect.yaml
ansible-collection/examples/receiver/update.yaml
ansible-collection/examples/receiver/validate_smtp.yaml
ansible-collection/examples/recipient/create.yaml
ansible-collection/examples/recipient/delete.yaml
ansible-collection/examples/recipient/enumerate.yaml
ansible-collection/examples/recipient/inspect.yaml
ansible-collection/examples/recipient/update.yaml
ansible-collection/inventory/group_vars/receiver/create.yaml
ansible-collection/inventory/group_vars/receiver/delete.yaml
ansible-collection/inventory/group_vars/receiver/inspect.yaml
ansible-collection/inventory/group_vars/receiver/update.yaml
ansible-collection/inventory/group_vars/receiver/validate_smtp.yaml
ansible-collection/inventory/group_vars/recipient/create.yaml
ansible-collection/inventory/group_vars/recipient/delete.yaml
ansible-collection/inventory/group_vars/recipient/inspect.yaml
ansible-collection/inventory/group_vars/recipient/update.yaml
ansible-collection/plugins/modules/receiver.py
ansible-collection/plugins/modules/recipient.py

Addition of receiver module for Ansible Galaxy

PB-8740: Receiver Module | SMTP

---

ansible-collection/docs/README.md
ansible-collection/docs/modules/schedule_policy.md
ansible-collection/examples/role/create.yaml
ansible-collection/examples/schedule_policy/create.yaml
ansible-collection/examples/schedule_policy/delete.yaml
ansible-collection/examples/schedule_policy/enumerate.yaml
ansible-collection/examples/schedule_policy/inspect.yaml
ansible-collection/examples/schedule_policy/update.yaml
ansible-collection/examples/schedule_policy/update_ownership.yaml
ansible-collection/inventory/group_vars/schedule_policy/create.yaml
ansible-collection/inventory/group_vars/schedule_policy/delete.yaml
ansible-collection/inventory/group_vars/schedule_policy/enumerate.yaml
ansible-collection/inventory/group_vars/schedule_policy/inspect.yaml
ansible-collection/inventory/group_vars/schedule_policy/update.yaml
ansible-collection/inventory/group_vars/schedule_policy/update_ownership.yaml
ansible-collection/plugins/modules/schedule_policy.py

**What this PR does / why we need it**: Add Ansible module, playbooks and doc for Schedule Policy object
Closes #PB-9199

PB-9199: Ansible module, playbooks and doc for Schedule Policy object

---

ansible-collection/README.md
ansible-collection/docs/README.md
ansible-collection/docs/modules/backup.md
ansible-collection/docs/modules/backup_location.md
ansible-collection/docs/modules/backup_schedule.md
ansible-collection/docs/modules/cloud_credential.md
ansible-collection/docs/modules/cluster.md
ansible-collection/docs/modules/receiver.md
ansible-collection/docs/modules/recipient.md
ansible-collection/docs/modules/resource_collector.md
ansible-collection/docs/modules/restore.md
ansible-collection/docs/modules/role.md
ansible-collection/docs/modules/rule.md
ansible-collection/docs/modules/schedule_policy.md
ansible-collection/galaxy.yml
ansible-collection/plugins/modules/auth.py
ansible-collection/plugins/modules/backup.py
ansible-collection/plugins/modules/backup_location.py
ansible-collection/plugins/modules/backup_schedule.py
ansible-collection/plugins/modules/cloud_credential.py
ansible-collection/plugins/modules/cluster.py
ansible-collection/plugins/modules/receiver.py
ansible-collection/plugins/modules/recipient.py
ansible-collection/plugins/modules/resource_collector.py
ansible-collection/plugins/modules/restore.py
ansible-collection/plugins/modules/role.py
ansible-collection/plugins/modules/rule.py
ansible-collection/plugins/modules/schedule_policy.py

Release branch merge to master 2.8.3

PB-9479: release for 2.8.3

---

ansible-collection/ansible.cfg
ansible-collection/examples/backup_schedule/enumerate.yaml
ansible-collection/inventory/group_vars/common/all.yaml
ansible-collection/plugins/modules/backup_schedule.py
ansible-collection/vm-protection-management.py

vm protection management script for GM

Vm protection management script

---

ansible-collection/retry-failed-backups.py

Update retry-failed-backups script to include on failed VM resources

---

ansible-collection/README.md
ansible-collection/plugins/modules/backup_schedule.py

- Update README with correct links
- Remove invalid field for backup and backup schedule update from the playbooks
Closes #PB-10254

PB-10254: Improvements

---

ansible-collection/examples/volume_resource_only_policy/inspect.yaml

Inspect with SPECIFIC tag for VRO was not working, made changes in playbook for it to work properly
Closes #
** CASE FOR SPECIFIC **
** CASE FOR ALL **

PB-11198: Correcting playbook for VRO inspect to work with Specific tag

---

ansible-collection/examples/volume_resource_only_policy/update.yaml
ansible-collection/inventory/group_vars/volume_resource_only_policy/update.yaml

Adding section for update ownership in case of VRO
Closes #
**Success case:**
**Failure Case:**

PB-11211: Adding missing section for updateOwnership in VRO

---

ansible-collection/examples/backup_schedule/delete.yaml
ansible-collection/examples/backup_schedule/delete_schedule.yaml
ansible-collection/examples/backup_schedule/enumerate.yaml
ansible-collection/plugins/modules/backup_schedule.py

Delete endpoint was missing uid, in case of simple delete in the param. 
Also improved the switch to choose between method DELETE and method POST _delete_.
https://purestorage.atlassian.net/browse/PB-11408

PB-11374: Delete endpoint fix | Backup Schedule

---

ansible-collection/docs/modules/volume_resource_only_policy.md
ansible-collection/examples/volume_resource_only_policy/enumerate.yaml
ansible-collection/inventory/group_vars/volume_resource_only_policy/enumerate.yaml
ansible-collection/plugins/modules/volume_resource_only_policy.py

please find the testing in the ticket:
https://purestorage.atlassian.net/browse/PB-11404?focusedCommentId=597880

PB-11404: Addition of enumerate options in VRO INSPECT_ALL

---

ansible-collection/plugins/modules/restore.py

output was not displayed in restore create:
final result after fix:
```json
TASK [Create restore] 
{
"ansible_loop_var": "item",
"changed": true,
"invocation": {
"module_args": {
"api_url": "http://10.13.199.97:31138",
"backup_object_type": null,
"backup_ref": {
"name": "nfs-attached-schedule-demo-40dd1a5-interval-2025-06-25-061755",
"uid": "108dcb63-2b24-4408-8456-1fb09ee31cb2"
},
"cluster": "self",
"cluster_name_filter": null,
"cluster_ref": {
"name": "self",
"uid": "460bdeb4-1bc3-47ec-86db-e1f0b1d52936"
},
"cluster_uid_filter": null,
"include_detailed_resources": false,
"include_resources": null,
"max_objects": null,
"name": "restore-test",
"name_filter": null,
"namespace_mapping": {},
"operation": "CREATE",
"org_id": "default",
"owners": null,
"rancher_project_mapping": null, …
```

PB-11454: output formatting | restore module
